### ISSUE TITLE
Remove Java Advanced Images JAI and ImageIO dependencies from Codebase

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#263]
to fix open tasks for [CQ 7142](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=7142)

**Comment by nprigour** [comment]
Hi @fgdrf,

The task link provided in you comment above seems not to be valid. Can you check and correct it.

**Comment by fgdrf** [comment]
@nprigour It might be only visible for PMC's

here is the excerpt : 

> The pure java version of these jars are included in net.refractions.udig.jai
> and net.refractions.udig.jai.macosx 
> 
> * clibwrapper_jiio.jar
> * jai_codec.jar
> * jai_core.jar
> * jai_imageio.jar
> * mlibwrapper_jai.jar
> 
> [..]
>
> No third-party source is intermingled with the project license material.
> All you need to do is exclude any jar file in the codebase.
> We noted three trouble spots perviously:
>
>   - Distribution of JAI and ImageIO 
>   - Placeholder Jars: not sure how to handle these

**Comment by fgdrf** [comment]
I'd like to collect ideas how we can resolve the open IP CQ and fix JAI/imageIO dependencies. My read is that JAI/imageIO is a "works-with" dependency and should not be part of the project itself. Right now we have a feature and bundles resolved via an update site from http://udig.refractions.net/files/update-jai/ (see target file). 

What about the following szenario:

Creating a product without features and bundles that have JAI/imageIO dependencies --> Raster, image and WMS would not be part of uDig product anymore. This "Demo" application has update compatibility to install all the other features from e.g. Refractions update site

What options else we have? What is the current state in GeoTools to run wihout JAI/imageIO, ist there a replacement in newer Versions of GT?

Your Feedback is warmly welcome

**Comment by fgdrf** [comment]
Made some progress and got an instance running without JAI but still with WMS and Feature support. Going to consolidate refactorings (e.g. split up style bundles into style and style.raster) and de-couple bundle dependencies (WMS -> GridCoverage). Going to publish a branch for this soon ..

**Comment by fgdrf** [comment]
@nprigour You are right, I messed up my classpath and fond severeal changes that were not correct. 

Started seperate bundles in another pull request (for simple style sld) : #269
