### ISSUE TITLE
standalone application development using udig

### ISSUE THREAD

**Issue by am2222** [locationtech/udig-platform#268]
Hi,
Is it possible to develop standalone applications using udig framework?If yes can you please share me some resources and etc to start with this framework?

**Comment by fgdrf** [comment]
Sure, you can integrade uDig into your own Application. We have some tutorials how to do so. Please  have a look to the Custom Applcation Tutorial http://udig.github.io/docs/dev/CustomApplication/CustomApplication.html

**Comment by am2222** [comment]
@fgdrf  thanks very much for your reply, as far as I am concerned this repository is only for development issues, is there any user groups, etc so I can use them in case of possible questions ?

**Comment by fgdrf** [comment]
Tutorials are kind of documentations and its possible to clone the repository to see how it works. However, feel free to send your questions to user-mailing list or the developer-mailing list:

* [user-mailinglist](https://www.locationtech.org/mailman/listinfo/udig-users)
* [developer-mailinglist](https://www.locationtech.org/mailman/listinfo/udig-dev)

Hope this helps

**Comment by am2222** [comment]
@fgdrf  thanks very much for youe help, I have one more questions, which repository is udigs main development?I am confused a bit when I search github I find more than one repository
thanks very much

**Comment by fgdrf** [comment]
main repository is this one (locationtech/udig-platform) and the others are forks of this (to work on contributions). See network : https://github.com/locationtech/udig-platform/network

**Comment by am2222** [comment]
@fgdrf  thanks very much for your helps. the problem here is that I am not much familier with RCP, I was wondering if I can find any modern UI components such as e4 sweet (or others) which I can use them with udig, I could not find anything yet.

**Comment by fgdrf** [comment]
Maybe its worth to have a look at the Jenkins Instance that provides a complete uDig product as a demo application. Download zip for your preferred platform from https://ci.eclipse.org/udig/job/uDig-master-CI/lastSuccessfulBuild/artifact/features/org.locationtech.udig-product/target/products/

NOTE: it doesn't provide a Java Runtime, you need to install it before.

PS: This product buidl from master is based on Eclipse E4 Luna (4.2)

**Comment by am2222** [comment]
@fgdrf  thanks very much, I am downloading it, my main problem is with UI and  if RCP supports RTL languages and even better if I can find some user friendly components for it with the variety of controls that exists for other languages such as c#

**Comment by am2222** [comment]
@fgdrf thanks , I looked at it, it was quite similar to udig, during my searches I found it is possible to use javafx in RCP applications as renderes, I might be useful in this case

**Comment by fgdrf** [comment]
@am2222 Actually udig-platform is the source reporsitory for uDig ;) 

Eclipse (which is the platform for uDig/the framework uDig is based on) has "Right to Left" support. Please try to start uDig with [-dir](http://help.eclipse.org/kepler/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/misc/bidi.html) in combination with `-nl` option. Just add options to udig_internal.ini file (located in your installation folder)
HTH

**Comment by am2222** [comment]
@fgdrf  thanks very much for your helps
