### ISSUE TITLE
Add Perspective switcher to default product configuration

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#277]
Miss it since udig upgraded zu Eclipse E4 Platform.

**Comment by erdalkaraca** [comment]
It seems that the perspective bar is not set to be shown in UDIGWorkbenchConfiguration .
See line 49.

**Comment by nprigour** [comment]
Hi @fgdrf 

What do you mean by perspective switcher? Do you mean the icon bars that usually appear at the top left of eclipse toolbar and allows to open and switch between perspectives (see icon below)?  
![image](https://user-images.githubusercontent.com/26147785/39235707-53ef038a-487f-11e8-818c-59c373d2f159.png)
 I doubt whether this was present in any previous versions of udig. Switching between perspectives always occurred via `Window-->open perspective` menu option

**Comment by fgdrf** [comment]
> I doubt whether this was present in any previous versions of udig

@nprigour You are right, product never had the switcher since release 1.2
* https://udig.github.io/docs/user/getting_started/Quickstart.html
* http://udig.refractions.net/confluence/display/EN/Quickstart.html

I guess I had the product in mind which integrated uDig :grin: 

> It seems that the perspective bar is not set to be shown in UDIGWorkbenchConfiguration .

@erdalkaraca Thanks for this hint, can you create a pull request? :smile:

**Comment by fgdrf** [comment]
Many Thanks @erdalkaraca !

fixed it with commit 26fcdc4
