### ISSUE TITLE
Unit Test failure after JTS update RingExtractorTest

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#295]
Update to geotools 19.x which implies JTS upgrade to 1.14.0 two test failing:
* org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge
* org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge2Rings

For now we skip these to resolve the problem with this issue

**Comment by fgdrf** [comment]
see #279

**Comment by nprigour** [comment]
Do we need this anymore or we should close it? It seems the issue with the failing tests has eventually been resolved
