### ISSUE TITLE
WMS GetFeatureInfo request is malformed

### ISSUE THREAD

**Issue by nmtoken** [locationtech/udig-platform#316]
When using udig (Version: 2.0.0), and trying to do a WMS GetFeatureInfo request, I get the following error:

    <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
    <ServiceException code="MissingParameterValue">
    msWMSLoadGetMapParams(): WMS server error. Missing required parameter CRS
    </ServiceException>
    </ServiceExceptionReport>

as per below screen shot

![gfi-malfromed](https://user-images.githubusercontent.com/1692891/46964834-0fe86280-d0a1-11e8-84bd-73d83d7f76ce.png)

The actual request sent is (xxx.xxx.xxx substituting for server name):

> http://xxx.xxx.xxx/cgi-bin/UGA_ARGI/ows?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=ARTISANC&FORMAT=image/png&LANGUAGE=eng&HEIGHT=602&J=256&REQUEST=GetFeatureInfo&I=300&WIDTH=813&BBOX=30.889154617208934,0.03824996332654984,33.29548059763911,1.820055916855415&STYLES=default&QUERY_LAYERS=ARTISANC&VERSION=1.3.0

Adding `&CRS=EPSG:4326&` to the end **AND** switching the BBOX axes to `BBOX=0.03824996332654984,30.889154617208934,1.820055916855415,33.29548059763911&` gives the expected response

**Comment by fgdrf** [comment]
[WMS spec for version 1.3.0](
http://portal.opengeospatial.org/files/?artifact_id=14416) states that CRS is an mandatory parameter for GetFeatureInfo Requests

**Comment by nmtoken** [comment]
Yes indeed,  A GetFeatureInfo request is the effectively the GetMap request (except the the request type is GetFeatureInfo) plus image (pixel) coordinates in the GetMap image for the point clicked on in the map, plus the layers to be queried, plus the information format.  The issue is that the request is automatically generated by udig, so I can't add the CRS parameter manually

**Comment by nprigour** [comment]
Hi @nmtoken ,

Can you explain the way (precisely steps) you issue the above mentioned request from within the udig application. I couldn't find a way to generate it. When I add a layer I can see only possibilities to select between a general wms request (usually targeting raster layers) and a wfs request targeting feature layers.
In the wms request the CRS is sent (checked against geoserver). On the other hand wfs request have a completely different format from the one you specify above.

**Comment by nmtoken** [comment]
Hi @nprigour, yes agree that the WMS GetMap operation does send the CRS otherwise I wouldn't get a map to click on, and to reiterate I am talking about WMS and not WFS.

Sorry haven't got UDIG on this PC but as per my screenshot, if you see the info option in the palette window on the right hand side, I'm using that info tool to do the on map selection, and it is making the malformed GetFeatureInfo request.

**Comment by nprigour** [comment]
OK @nmtoken,

I tried to perform the steps as mentioned above using a geoserver 2.13 wms service . Indeed it seems that the request sent does not include CRS info. However information about the feature clicked is correctly returned to the info view. Of course it is possible that geoserver is less restrictive regarding the actual information needed during a getFeatureInfo request. Is it possible to provide some more information regarding the type of wms server you communicate with and if there is a way to access it for testing?

**Comment by nmtoken** [comment]
@mprins MapServer is working correctly because the GetMap operation is generating the correct map, the issue is with the GetFeatureInfo  operation.  MapServer version used here is 7.2.0 so https://mapserver.org/ogc/wms_server.html#wms-1-3-0-support is not an issue

**Comment by nmtoken** [comment]
@nprigour I'm using MapServer.  The issue is with UDIG not following the WMS standard, not with the server.  GeoServer has an option _Strict CITE compliance_ do you have that enabled in your test service? When I do a GetFeatureInfo request on GeoServer with _Strict CITE compliance_ set I don't get a result if I omit the CRS.

**Comment by fgdrf** [comment]
fixed with [milestone 2.1.0](https://github.com/locationtech/udig-platform/milestone/2)
