### ISSUE TITLE
Zoom/Pan flicker when using multi-point create tools. 

### ISSUE THREAD

**Issue by jsvrcek** [locationtech/udig-platform#334]
When using the create Polygon or Fill Area tools the image background will refresh an old render creating a flicker.  It is not a white flicker like a refresh, but rather it loads a new image, then loads an old image, then loads a newer image.  This seems to be caused by the EditToolHandler repaint() method.  Specifically the edit tools listeners will fire a repaint request to the ViewportPane at the same time as the ViewportPane lifecycle is repainting.  

To reproduce:
-  add a raster background (such as a OMS mapnik tile layer) or a tif.  
- Add a polygon layer.  
- Expand create (in the right hand tool bar).
- Select Create Polygon (no need to actually click the map).
- Zoom or pan the map and observe the change (if tiles aren't yet cached it will at first appear white, but then the stuttering will appear).

**Comment by fgdrf** [comment]
Thanks for reporting! Looks like you spotted an issued and found Code where to fix it. Would you provide a fix for this?
