### ISSUE TITLE
macOS run error

### ISSUE THREAD

**Issue by blissvisitor** [locationtech/udig-platform#353]
After I installed 2.0,When I run the app,Alert a error :The Udig_internal executable launcher was unable to locate its 
companion shared library.

**Comment by fgdrf** [comment]
It looks like unzipping creates bad attibutes on some files. Please try
`xattr -c udig.app` 
and try again to launch app.

HTH

**Comment by blissvisitor** [comment]
Thank you very much! It's worked.
