### ISSUE TITLE
Moved this PR into `in-progress` state, since I need to fix comments and probably to add the old version / function that will allow to get resolutions by the `GDALDataset.TYPE`

### ISSUE THREAD

**Issue by Robert-hasz** [locationtech/udig-platform#362]
Moved this PR into `in-progress` state, since I need to fix comments and probably to add the old version / function that will allow to get resolutions by the `GDALDataset.TYPE`

_Originally posted by @pomadchin in https://github.com/locationtech/geotrellis/pull/3125_

**Comment by Robert-hasz** [comment]
[unplug3.pdf](https://github.com/locationtech/udig-platform/files/3792185/unplug3.pdf)

**Comment by fgdrf** [comment]
not related to uDig project
