### ISSUE TITLE
Request for Change : Discontinue support for 32bit platforms

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#366]
This is open for discussion to remove support for Windows 32bit and Linux 32bit platforms as we did for MacOSX (due to upgrade to newer Eclipse Release)

This would help to speed up the build and reduce required discspace in both, target folders and .m2 repositories.

Please let us know your point of view

**Comment by nprigour** [comment]
To be honest I am still working with 32bit version(!!) and I would prefer to keep the 32bit **at least for windows systems**.  Maybe until we upgrade to an newer eclipse version or newer Java version since from what I have seen latest builds of eclipse are also not available for 32bit

**Comment by fgdrf** [comment]
related to #378 32bit platforms are not supported anymore by Eclipse Platform.

I'd vote to move on and support Java 11 rather than older OS 32bit platforms (we cannot test anyway)
