### ISSUE TITLE
uDig 2.0.0.RC1 freezes on MacOS

### ISSUE THREAD

**Issue by fgdrf** [locationtech/udig-platform#374]
@silviafranceschi reported an issue (https://github.com/uDig/udig-extras/issues/1) :

I am trying to run uDig 2.0.0.RC1 on MacOS with operating system Catalina and java JRE Java8: 1.8.0_241.
I can install it but when I start it all seems to work but nothing can be done from the GUI, all freezes and I have to exit from the icon of the application in the docker.

**Comment by fgdrf** [comment]
First try was to prepare installed udig.app with command shown in _Originally posted by @fgdrf in https://github.com/locationtech/udig-platform/issues/353#issuecomment-524633450_

lots of messages such as:

`!ENTRY org.eclipse.update.configurator 4 0 2020-01-28 16:59:14.653
!MESSAGE Could not install bundle plugins/org.apache.batik.util.gui_1.7.0.v200903091627.jar   A bundle is already installed with the name "org.apache.batik.util.gui" and version "1.7.0.v200903091627" 
`

were logged and we tried to configure Eclipse with an additional entry for vmargs as stated [here](https://wiki.eclipse.org/Equinox/p2/FAQ#Why_are_my_uninstalled_bundles_being_reloaded.21.3F)

`-Dorg.eclipse.update.reconcile=false`

**Comment by fgdrf** [comment]
@silviafranceschi @moovida Is this issue fixed with #378 we merged recently? If so, please close it ;)

**Comment by moovida** [comment]
Yup, the product build now runs. Waiting for the official release to test this. Reopening in case it doesn't work.
