### ISSUE TITLE
print map to pdf failed when the select print file is not exists on windows 

### ISSUE THREAD

**Issue by jaan-git** [locationtech/udig-platform#435]
https://github.com/locationtech/udig-platform/blob/54f29702cecf16b3a4bfb495ba0332926057010f/plugins/org.locationtech.udig.printing.ui/src/org/locationtech/udig/printing/ui/internal/PrintAction.java#L77
When the select print file is exists , print function works; But if the select print file is not exists , printing is not functioning properly and it prompts 'there is  a lock on the file'.

**Comment by fgdrf** [comment]
Quite interesting, going to have a look at it

Looks like I've provided a patch 5 years ago (https://github.com/locationtech/udig-platform/commit/a11ac49908809641c226fb87343e20d060b0dda5) an wondering what the original problem..

Could you provide a patch as a developer?

**Comment by fgdrf** [comment]
Many Thanks for reporting this issue and providing a fix!
