### ISSUE TITLE
uDig right-pane help doesn't work with English

### ISSUE THREAD

**Issue by dwadler** [locationtech/udig-platform#454]
Clicking on any of the topics like "Overview" brings up the help window but it comes up with "Topic not found" and clicking on any of the items topic list shows a 127.0.0.1 URL on the bottom but doesn't do anything.

I don't know if org.locationtech.udig.help_2.3.0.202105192119.jar is supposed to be picked up and is supposed to have any "EN" files, but I only see 'FR', 'EU', 'ES' and a few 'IT' files.

(starting with 'udig.bat -nl de' brings up the welcome pane with German contents but clicking on any of them brings up the English help which doesn't work)

![image](https://user-images.githubusercontent.com/7352808/118889434-2004f600-b8cb-11eb-8430-fa674bcd0c41.png)

**Comment by fgdrf** [comment]
@dwadler have you tested with fix #452 and local build with update of documentations with sphinx (see https://github.com/locationtech/udig-platform/blob/master/docs/readme.txt)?

**Comment by dwadler** [comment]
There have been too many moving parts the past two days!
It works like a charm now after downloading the latest uDig code and building in the Windows Linux Subsystem instead of building natively on Windows.
Separately, the IBM JDBC driver is now downloadable from the Maven central repository - I will look into doing this.
