### ISSUE TITLE
Resolve Maven Project Build Lifecycle Mapping Problem of plugin 'org.locationtech.udig.style.ui'

### ISSUE THREAD

**Issue by sschulz92** [locationtech/udig-platform#499]
Within my Eclipse I have 4 errors reported which are all about the plugin "org.locationtech.udig.style.ui". Within this issue I would like to request a fix so that the Eclipse IDE is not reporting this issues anymore.

![image](https://user-images.githubusercontent.com/89982771/134361716-bb23a2b7-412f-4b5b-a0aa-8bd1923b831d.png)

![image](https://user-images.githubusercontent.com/89982771/134361753-efef3b77-be7d-4574-bd20-bdc68c78101e.png)

The view "Problems" shows them all like this:

![image](https://user-images.githubusercontent.com/89982771/134361641-0c8fe63e-8406-40ce-b452-354d0f680f90.png)

**Comment by fgdrf** [comment]
I guess this is because I check in .project file with maven2Nature (which is not supported by uDig at the moment). I'd suggest to remove 
```<nature>org.eclipse.m2e.core.maven2Nature</nature>```

```		<buildCommand>
			<name>org.eclipse.m2e.core.maven2Builder</name>
			<arguments>
			</arguments>
		</buildCommand>
``` from style.ui .project file.

doc-module has the same "problem" where mentioned elements are confiigured.
