### ISSUE TITLE
GitHub action build is failing due to the SpotBugs plugin

### ISSUE THREAD

**Issue by sschulz92** [locationtech/udig-platform#557]
Hey, since the newest changes to the GitHub Action workflow, the builds are failing :(

```
Error: HttpError: Resource not accessible by integration
```

This error is logged at the end of step `Run jwgmeligmeyling/spotbugs-github-action@v1.2` - can you have a look please @fgdrf ?

**Comment by fgdrf** [comment]
Ok, IMO a configuration change for Repositories of Locationtech-Organization is required, I've filed an issue in bugzilla https://bugs.eclipse.org/bugs/show_bug.cgi?id=576565

**Comment by fgdrf** [comment]
removed action again - nothing to do right now
